### ISSUE TITLE
Autosuggest\Search endpoints using contains do not return results for some searches

### ISSUE THREAD

**Issue by seyilonge-nci** [NCIOCPL/glossary-api#118]
### Issue description
*Autosuggest and Search endpoints using contains does not return results when search string contains spaces*

> **ESTIMATE** 

### Steps to reproduce the issue

1.  Make a call to https://webapis-dev.cancer.gov/glossary/v1/Autosuggest/Cancer.gov/Patient/en/node%20biopsy?matchType=Contains&size=1000 or https://webapis-dev.cancer.gov/glossary/v1/Terms/search/Cancer.gov/Patient/en/node%20biopsy?matchType=Contains&size=1000

### What's the expected result?
Should return results matching search text

### What's the actual result?
```json
{
  "meta": {
    "totalResults": 0,
    "from": 0
  },
  "results": [],
  "links": null
}
```

#### Result from swagger
- ![Screenshot](https://user-images.githubusercontent.com/58226882/81574322-a7905e80-9373-11ea-86ec-5858089061bb.png)

#### Results showing same search conducted on [Cancer.gov](https://www.cancer.gov/publications/dictionaries/cancer-terms/search?contains=true&q=node+biopsy)
- Autosuggest
-![Screenshot](https://user-images.githubusercontent.com/58226882/81574830-4c12a080-9374-11ea-8106-943b93b6a565.png)
- Search
-![Screenshot](https://user-images.githubusercontent.com/58226882/81575137-ae6ba100-9374-11ea-837c-a03319913609.png)

**Comment by bryanpizzillo** [comment]
@zhuomingao - Can you triage this please? Make sure the index will handle this, then check the query.

**Comment by zhuomingao** [comment]
after changes to index mapping and loader, search contains now works as prod.

for autosuggest contain, ES query needs to be:
curl -XPOST http://SERVER_NAME/glossaryv1/terms/_search -H 'Content-Type: application/x-ndjson'   -d '{
  "query": {
    "bool" : {
      "must" : 
        [{"term" : { "language" : "es" }},
        {"term" : { "dictionary" : "Cancer.gov" }},
        {"term": { "audience": "Patient"}},
        {"match_phrase":{"term_name._autocomplete":"cutáneo"}}
        ],
         "must_not" :  {"prefix" : {"term_name" : "cutáneo"}}
      }
    }
,"sort": ["term_name"]
, "_source": ["term_id", "term_name"]
, "from": 0
, "size": 10
}'
as in https://github.com/NCIOCPL/glossary-api/wiki/Elastic-search-Query

**Comment by blairlearn** [comment]
We're getting closer.  "node biopsy" works, but searching for "cel" doesn't match production.  In production, autosuggest for terms containing "cell" matches both "adoptive cell transfer" and "adult T-**_cell_** leukemia/lymphoma".

The API does not match the latter.
