### ISSUE TITLE
Change includedFields to includeAdditionalInfo on Search and Expand endpoints

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/glossary-api#132]
### Issue description
Devs on the team are really confused about how to use the includedFields endpoint. Additionally, there are certain fields that we force anyway (non-nullable like audience), this is more confusing because the shape of the response does not change, just the data in that response. For example if there are 10 media items, when not specifying the includedFields, you get `media: []` back making seem like there is no media for that item.

What would be easier is to just have a flag that indicates that you want this additional information (relatedResources and media) returned back with a search or expand response. (I don't want to call it includeRelatedInfo because it will be confused as to if it only includes relatedResources.)

> **ESTIMATE** NN

### What's the expected change?
-

### What's the current functionality?
-

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by blairlearn** [comment]
To be clear, the `includeAdditionalInfo` parameter is a _replacement_ for `includedFields`?  This is a breaking change.

**Comment by bryanpizzillo** [comment]
> To be clear, the `includeAdditionalInfo` parameter is a _replacement_ for `includedFields`? If there are any external users, this will be a breaking change. (Unlikely, since the API has not been publicized.)

Yep. Let's assume there are no external users left. This was a bad parameter and it overly complicates the code as well. Once the API is promoted, etc. then we can worry about multiple versions. (and deprecation schedules, etc)
