### ISSUE TITLE
Letters with diacritics are treated as "not a letter."

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/glossary-api#137]
### Issue description
Letters with diacritics, e.g. `Á`, are grouped with "not a letter" instead of the normalized letter.

This is an issue in the loader.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/espanol/publicaciones/diccionario
2. Click on the `#` in the AtoZ list.
3. Scroll down past the terms starting with `1`

### What's the expected result?
- There should be no terms starting with letters.

### What's the actual result?
- Terms with letters appear in the list, starting with `ácido` and continuing through `úvula palatina`

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by bkline** [comment]
Changed requirements implemented on DEV. New test set attached.

[glossary.zip](https://github.com/NCIOCPL/glossary-api/files/5282965/glossary.zip)

**Comment by blairlearn** [comment]
This has already been implemented.
