### ISSUE TITLE
Glossary Term Definitions aren't showing for Genetics Summaries

### ISSUE THREAD

**Issue by venglisch** [NCIOCPL/glossary-api#143]
### Issue description
When a glossary link in a genetics summary is clicked, the glossary definition does not show.  See for instance the summary
https://www.cancer.gov/types/colorectal/hp/colorectal-genetics-pdq
and click on the glossary link "familial".
 
> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Open a genetics HP summary
2. Find a glossary term link
3. Click the link

### What's the expected result?
- The expected result is for the glossary definition to be displayed within a modal window

### What's the actual result?
- Nothing is happening

### Additional details / screenshot
- The call to the dictionary API returns an error
https://webapis.cancer.gov/glossary/v1/Terms/genetics/HealthProfessional/en/460148?useFallback=true

### Related Tickets
* Issue https://github.com/NCIOCPL/cgov-digital-platform/issues/3007

**Comment by blairlearn** [comment]
Closed by #144
