### ISSUE TITLE
Create getGlossaryTerm endpoint

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/glossary-api#3]
* This should respond to `/glossary/v1/term{id}`
* Simply return a fake term for now.
* Needs to return a JSON structure which can be used from multiple languages.

**Comment by akavalloor** [comment]
There is change in the endpoint url.
Instead of responding to /glossary/v1/term{id}, getGlossaryTerm will respond to /glossary/v1/term/{dictionary}/{audience}/{language}/{id}
