### ISSUE TITLE
Set host name in swagger docs to reflect the server the documents were requested from.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/glossary-api#4]
The swagger document for the API should reflect the specific server it was retrieved from instead of presenting a list of servers or always referring to localhost.

**Comment by bryanpizzillo** [comment]
![image](https://user-images.githubusercontent.com/11215649/74977413-a72d9a80-53f8-11ea-92fe-a083f1e07244.png)

^^^ It looks like this got fixed at some point.
