### ISSUE TITLE
Data Issues with GlossaryTerm objects

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/glossary-api#60]
The data in the ElasticSearch backend does not match the class structures of the API. This may be issues with the mapping or the loader. This ticket is a rollup for all the issues encountered in the API.

### GlossaryTerm `pronunciation` property
- [x] When a GlossaryTerm does not have a `audio` property and it does not have a `key` property the `pronunciation` property should be null, or not included at all in the document to be indexed. 
* Currently it appears as:
          ```
          {
            "pronunciation": {
               "audio": null,
               "key": null,
            }
          }
          ```
* It should appear as:
          ```
          {
            "pronunciation": null
          }
          ```
- [x] The `audio` property of a GlossaryTerm’s pronunciation property should be an absolute URL. 
* Once nci-media has been implemented this URL should point to the nci-media.cancer.gov URI for the audio file where that tier is publishing to. For example it could look like `https://nci-media-dev.cancer.gov/audio/pdq/731498.mp3` for the CDR dev tier.
* Until that is ready, use the current *production* server and path for audio files, no matter the tier. E.g. `https://www.cancer.gov/PublishedContent/Media/CDR/media/731498.mp3`

### LinkResource objects
- [x] The url property for a DrugSummary related resource types should be an absolute URI. Use `https://www.cancer.gov` as the prefix on all tiers.
- [x] The url property for a Summary related resource types should be an absolute URI. Use `https://www.cancer.gov` as the prefix on all tiers.
### GlossaryResource objects
- [x] GlossaryResource objects do not match the wiki and need to be updated to match the Wiki/API class model
* Remove the `url` property
* Add the `id` property which holds the int version of the CDRID the referenced glossary term
* Add the `audience` property for the audience of the referenced glossary term
* ~~Add the `dictionary` property for the dictionary of the referenced glossary term~~
* Add the `pretty_url_name` property for the pretty url name of the referenced glossary term

### Video Issues
- [x] The `caption` property should not be an array, but a scalar. (I.E. It should not be an array.)

### Image Issues
- [x] The `caption` property should not be an array, but a scalar. (I.E. It should not be an array.)
- [x] Add a `image_sources` property of to the Image object to hold the various published sizes. 

* There is no source URL on the image object. The class model in the wiki specifies that the `ref` property is to be a URL. This does not match up with the `ref` property currently being published on the video.  Additionally, an image can be published as multiple sizes, so a single field is not a good idea from the get-go.

* This should be an array of objects that have the following properties:
   * `size` - a string indicating the file size
      * For now this will be `750` or `571`
   * `src` - An absolute URI to the file. 
      * Once nci-media has been implemented this URL should point to the nci-media.cancer.gov URI for the image file where that tier is publishing to. For example it could look like `https://nci-media-dev.cancer.gov/images/pdq/CDR466533-750.jpg` for the CDR dev tier.
      * Until that is ready, use the current *production* server and live path for image files, no matter the tier. E.g. `https://www.cancer.gov/images/cdr/live/CDR466533-750.jpg`
   * For now we know we use 750 & 571 in our APP, so just include only those two for now.

**Comment by bkline** [comment]
> Add a[n] `image_srcs` property of a GlossaryTerm’s pronunciation property to hold the various published sizes.

I assume you meant "... to the `media` property for images ... (images aren't used for pronunciation -- unless we're going to start illustrating lip/tongue positions). :-)

**Comment by bkline** [comment]
> Add the dictionary property for the dictionary of the referenced glossary term

The link to the related glossary term doesn't specify a dictionary.

**Comment by bkline** [comment]
I've got another load up, which I think addresses these issues (except the dictionary for related glossary terms, which isn't available -- see comment above). For the absolute media URLs, I've done the future version, as that's the more complicated of the two to implement. Once we're satisfied that I've got it right, I'll (temporarily) switch over to the version we need until the media server's in place. We should be able to close this ticket when

- Bryan signs off on the fixes
- Volker updates the mapping document
- the wiki gets the updates

**Comment by bkline** [comment]
I may have come to the wrong conclusion in my earlier reading of
> There is no source URL on the image object. The class model in the wiki specifies that the `ref` property is to be a URL. This does not match up with the `ref` property currently being published on the video. Additionally, an image can be published as multiple sizes, so a single field is not a good idea from the get-go.

above. I had taken that as implying the the new `image_srcs` array was a _replacement_ for the `ref` property. However, looking at the revised diagram, it seems that the `ref` property is still required. If you confirm, I'll add it back in.

**Comment by bryanpizzillo** [comment]
> > Add a[n] `image_srcs` property of a GlossaryTerm’s pronunciation property to hold the various published sizes.
> 
> I assume you meant "... to the `media` property for images ... (images aren't used for pronunciation -- unless we're going to start illustrating lip/tongue positions). :-)

Yes. I thought I had caught all of the copy and paste issues. Sorry. I updated the description accordingly.

**Comment by bryanpizzillo** [comment]
> I may have come to the wrong conclusion in my earlier reading of
> 
> > There is no source URL on the image object. The class model in the wiki specifies that the `ref` property is to be a URL. This does not match up with the `ref` property currently being published on the video. Additionally, an image can be published as multiple sizes, so a single field is not a good idea from the get-go.
> 
> above. I had taken that as implying the the new `image_srcs` array was a _replacement_ for the `ref` property. However, looking at the revised diagram, it seems that the `ref` property is still required. If you confirm, I'll add it back in.

That is correct that ref still exists. Video had it, so I thought media should be consistent. TBH I don't know if ref is needed on either media type, but it is probably helpful for debugging, so we can keep it in.

**Comment by bkline** [comment]
OK, `ref` is back in for images.

**Comment by bkline** [comment]
Just out of curiosity, what was the thinking behind having `image_srcs` _not_ be the following?

```
          "image_srcs" : [
            {
              "size" : "original",
              "src" : "https://nci-media-dev.cancer.gov/images/pdq/CDR768574.jpg"
            },
            {
              "size" : "571",
              "src" : "https://nci-media-dev.cancer.gov/images/pdq/CDR768574-571.jpg"
            },
            {
              "size" : "750",
              "src" : "https://nci-media-dev.cancer.gov/images/pdq/CDR768574-750.jpg"
            }
          ]
 ```

**Comment by bryanpizzillo** [comment]
@bkline It looks like `dictionary` and `audience` are missing from the the source document sent to Elasticsearch.
Example: http://ncias-d1592-v:9400/glossaryv1/terms/44759_cancer.gov_en_patient

**Comment by bkline** [comment]
`dictionary` and `audience` restored

**Comment by bryanpizzillo** [comment]
> Just out of curiosity, what was the thinking behind having `image_srcs` _not_ be the following?
> 
> ```
>           "image_srcs" : [
>             {
>               "size" : "original",
>               "src" : "https://nci-media-dev.cancer.gov/images/pdq/CDR768574.jpg"
>             },
>             {
>               "size" : "571",
>               "src" : "https://nci-media-dev.cancer.gov/images/pdq/CDR768574-571.jpg"
>             },
>             {
>               "size" : "750",
>               "src" : "https://nci-media-dev.cancer.gov/images/pdq/CDR768574-750.jpg"
>             }
>           ]
> ```

I did not see that we actually used the original dimensions. Technically we don't for the dictionary, but @blairlearn pointed out that for summaries the exact same markup uses the original for the enlarge. For the dictionary the 750 size is used for enlarge. 

So the summary is, please add original to the list.

**Comment by bkline** [comment]
original added

**Comment by venglisch** [comment]
> > Add the dictionary property for the dictionary of the referenced glossary term
> 
> The link to the related glossary term doesn't specify a dictionary.

I vaguely remember that we said a link to a dictionary term is only allowed within its type of dictionary (HP to HP, Glossary to Glossary, etc).

**Comment by bkline** [comment]
Well, the mapping document specifies _if audience = @audience_ but not _if dictionary = @Dictionary_.

**Comment by venglisch** [comment]
Ah, I guess that's what I remembered - staying within the audience.  I did say "vaguely". :-)

**Comment by bryanpizzillo** [comment]
Ok, So based in research from @venglisch:
>Related Glossary:
>The CDR allows to link to any glossary term regardless of which dictionary it is in.  However, the vendor filter strips out a related glossary term if its language and audience (i.e. dictionary) isn’t matching.

Given this fact, the Dictionary property is no longer needed for a GlossaryResource.

**Comment by bryanpizzillo** [comment]
I am going to close this all these items are looking good.
