### ISSUE TITLE
Update ES Autosuggest Query Service test file

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/glossary-api#78]
The ESAutosuggestQueryService test file does not have "Test" included in the name. For consistency's sake, it should be renamed to ESAutosuggestQueryServiceTest.

**Comment by blairlearn** [comment]
I'm kinda surprised to learn that file even exists already.  Implementing tests is part of #36 (there are currently none); I'm going to close this ticket and fold it into that one.
