### ISSUE TITLE
The root swagger page shows functions for the "Swagger Petstore"

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/glossary-api#90]
### Issue description
* Viewing the base swagger document without a `url=` parameter shows the swagger document for the "Swagger Petstore" demo.

### Steps to reproduce the issue

1.  Start the API project (either `dotnet run` or in VS code debug view)
2. Go to http://localhost:5000/index.html (no additional parameters) 

### What's the expected result?
- Swagger page for the glossary API.

### What's the actual result?
- The swagger page for http://petstore.swagger.io/v2/swagger.json

### Additional details / screenshot
- ![Screenshot](https://user-images.githubusercontent.com/21063180/74181598-9d917f00-4c0f-11ea-8af2-609e4096d452.png)

**Comment by bryanpizzillo** [comment]
It looks like [11.17.7](https://github.com/RicoSuter/NSwag/pull/1331) fixes this. We are on 11.17.1. The newest is 13.2.3. We should move to something newer.
